/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "on-surface-variant": "#5a403c",
        "primary-fixed-dim": "#ffb4a8",
        "surface-container": "#f0eee9",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#745c00",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f2f1ec",
        "tertiary-container": "#324456",
        "surface-container-low": "#f5f3ee",
        "outline": "#8e706b",
        "on-error-container": "#93000a",
        "on-primary-container": "#ff907f",
        "surface-container-highest": "#e4e2dd",
        "primary-container": "#8b0000",
        "on-background": "#1b1c19",
        "on-tertiary-fixed-variant": "#36485b",
        "secondary": "#735c00",
        "on-surface": "#1b1c19",
        "on-primary": "#ffffff",
        "primary": "#610000",
        "on-primary-fixed": "#410000",
        "surface-bright": "#fbf9f4",
        "outline-variant": "#e3beb8",
        "background": "#fbf9f4",
        "on-secondary-fixed-variant": "#574500",
        "on-secondary-fixed": "#241a00",
        "surface-tint": "#b52619",
        "surface-variant": "#e4e2dd",
        "tertiary": "#1b2e3f",
        "inverse-primary": "#ffb4a8",
        "secondary-fixed-dim": "#e9c349",
        "inverse-surface": "#30312e",
        "tertiary-fixed-dim": "#b5c8df",
        "on-secondary": "#ffffff",
        "surface-dim": "#dbdad5",
        "surface-container-high": "#eae8e3",
        "on-error": "#ffffff",
        "tertiary-fixed": "#d1e4fb",
        "secondary-container": "#fed65b",
        "on-tertiary-fixed": "#091d2e",
        "on-tertiary": "#ffffff",
        "surface": "#fbf9f4",
        "secondary-fixed": "#ffe088",
        "on-tertiary-container": "#9eb1c7",
        "on-primary-fixed-variant": "#920703",
        "primary-fixed": "#ffdad4",
        "on-tertiary-fixed-variant": "#36485b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        "margin-mobile": "16px",
        gutter: "24px",
        "margin-desktop": "48px",
        sm: "8px",
        xl: "32px",
        xs: "4px",
        lg: "24px",
        base: "4px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-sm": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "label-md": ["Montserrat", "sans-serif"],
        sans: ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
